import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { getAIReviewHistory } from "../services/aiService.js";
import { getErrorMessage } from "../utils/getErrorMessage.js";
import DifficultyBadge from "../components/problems/DifficultyBadge.jsx";
import { Sparkles, X } from "lucide-react";

const ReviewHistoryPage = () => {
  const [reviews, setReviews] = useState([]);
  const [selectedReview, setSelectedReview] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchReviews = async () => {
    try {
      setIsLoading(true);
      setError("");
      const response = await getAIReviewHistory();
      setReviews(response.data || []);
    } catch (err) {
      setError(getErrorMessage(err) || "Failed to fetch review history");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReviews();
  }, []);

  return (
    <article className="problems-page-container card-fade-in">
      <header className="problems-hero" style={{ background: "linear-gradient(135deg, #4f46e5 0%, #3730a3 100%)", boxShadow: "0 16px 40px rgba(79, 70, 229, 0.12)" }}>
        <div className="hero-content">
          <p className="eyebrow" style={{ color: "#ffd480" }}>AI Review Assistant</p>
          <h1>Your AI Code Reviews</h1>
          <p className="hero-subtext" style={{ color: "#e0e7ff" }}>
            A complete history of code reviews generated by Google Gemini AI. Analyze complexity, bugs, edge cases, and best practices.
          </p>
        </div>
      </header>

      {isLoading ? (
        <div className="page-status" style={{ padding: "4rem 0" }}>
          <div className="spinner" style={{ margin: "0 auto 1.5rem" }}></div>
          <p>Loading your AI review history...</p>
        </div>
      ) : error ? (
        <div className="alert error">{error}</div>
      ) : reviews.length === 0 ? (
        <div className="empty-state" style={{ padding: "5rem 2rem", border: "1px solid #e2e8f0", borderRadius: "24px", background: "#ffffff" }}>
          <Sparkles size={40} style={{ margin: "0 auto 1rem", display: "block", color: "#7c3aed" }} />
          <h3 style={{ margin: "0 0 0.5rem 0" }}>No Reviews Yet</h3>
          <p style={{ color: "#64748b", margin: 0 }}>
            When you solve problems in the workspace, click the "AI Review" button to get smart feedback.
          </p>
          <Link to="/problems" className="primary-button" style={{ display: "inline-flex", marginTop: "1.5rem" }}>
            Explore Problems
          </Link>
        </div>
      ) : (
        <div className="table-responsive">
          <table className="problems-table">
            <thead>
              <tr>
                <th>Problem</th>
                <th>Difficulty</th>
                <th>Language</th>
                <th>Reviewed At</th>
                <th style={{ textAlign: "right" }}>Report</th>
              </tr>
            </thead>
            <tbody>
              {reviews.map((rev) => (
                <tr key={rev._id}>
                  <td>
                    <Link 
                      to={`/problems/${rev.problemId?._id || rev.problemId}`}
                      className="problem-link-title"
                    >
                      {rev.problemId?.title || "Deleted Problem"}
                    </Link>
                  </td>
                  <td>
                    {rev.problemId?.difficulty ? (
                      <DifficultyBadge difficulty={rev.problemId.difficulty} />
                    ) : (
                      <span className="verdict-badge">—</span>
                    )}
                  </td>
                  <td style={{ fontWeight: 700, color: "#475569" }}>
                    {rev.language.toUpperCase()}
                  </td>
                  <td style={{ color: "#64748b", fontSize: "0.9rem" }}>
                    {new Date(rev.createdAt).toLocaleString()}
                  </td>
                  <td style={{ textAlign: "right" }}>
                    <button
                      className="solve-action-btn"
                      style={{ background: "#4f46e5" }}
                      onClick={() => setSelectedReview(rev)}
                      type="button"
                    >
                      View Report
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Detailed Review Modal / Overlay */}
      {selectedReview && (
        <div className="submission-detail-overlay">
          <div className="submission-detail-modal" style={{ maxWidth: "800px", width: "90%", background: "#ffffff", color: "#1e293b" }}>
            <header className="modal-header" style={{ borderBottom: "1px solid #e2e8f0", padding: "1.25rem 1.5rem" }}>
              <div>
                <h3 style={{ margin: 0, color: "#0f172a", fontSize: "1.25rem" }}>
                  AI Review: {selectedReview.problemId?.title || "Deleted Problem"}
                </h3>
                <span className="history-date" style={{ fontSize: "0.85rem", color: "#64748b" }}>
                  Generated on {new Date(selectedReview.createdAt).toLocaleString()}
                </span>
              </div>
              <button
                className="close-button"
                onClick={() => setSelectedReview(null)}
                type="button"
                aria-label="Close review"
              >
                <X size={22} />
              </button>
            </header>

            <div className="modal-body" style={{ maxHeight: "70vh", overflowY: "auto", padding: "1.5rem" }}>
              <div className="modal-meta-grid" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem", background: "#f8fafc", padding: "1rem", borderRadius: "12px", border: "1px solid #e2e8f0" }}>
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <span style={{ fontSize: "0.8rem", color: "#64748b", fontWeight: 700, textTransform: "uppercase" }}>Language</span>
                  <strong style={{ color: "#0f172a" }}>{selectedReview.language.toUpperCase()}</strong>
                </div>
                <div style={{ display: "flex", flexDirection: "column" }}>
                  <span style={{ fontSize: "0.8rem", color: "#64748b", fontWeight: 700, textTransform: "uppercase" }}>Problem Link</span>
                  {selectedReview.problemId?._id ? (
                    <Link to={`/problems/${selectedReview.problemId._id}`} style={{ color: "#4f46e5", fontWeight: 700, textDecoration: "underline" }}>
                      Go to Workspace
                    </Link>
                  ) : (
                    <strong style={{ color: "#94a3b8" }}>Unavailable</strong>
                  )}
                </div>
              </div>

              <div className="modal-code-section" style={{ marginTop: "1.5rem" }}>
                <h4 style={{ color: "#0f172a", fontSize: "1rem", fontWeight: 800, marginBottom: "0.75rem" }}>Submitted Code</h4>
                <pre className="modal-code-display" style={{ background: "#1e1e1e", color: "#d4d4d4", padding: "1rem", borderRadius: "12px", overflowX: "auto", fontSize: "0.9rem" }}>
                  <code>{selectedReview.code}</code>
                </pre>
              </div>

              <div className="ai-review-section" style={{ marginTop: "2rem", borderTop: "1px solid #e2e8f0", paddingTop: "1.5rem" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "1rem" }}>
                  <Sparkles size={20} style={{ color: "#7c3aed", flexShrink: 0 }} />
                  <h3 style={{ margin: 0, color: "#0f172a", fontSize: "1.2rem" }}>AI Feedback &amp; Recommendations</h3>
                </div>
                <div className="ai-review-markdown">
                  <ReactMarkdown>{selectedReview.review}</ReactMarkdown>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </article>
  );
};

export default ReviewHistoryPage;
